### ISSUE TITLE
Can't verify any QR

### ISSUE THREAD

**Issue by Epitaffio** [ministero-salute/dcc-utils#1]
# Issue content
Hey there, first of all, thank you for the repo.

I am trying to use this library but it seems that besides the provided QR I can't veirfy any other one. All the QR I am trying are taken from the IO italian app.

The cose library keep returning this error: "Signature missmatch". To do the verification I have tried to use the provided cert and the one from the government (https://get.dgc.gov.it/v1/dgc/signercertificate/update) with the same result.

I am also having problem using the tool provided in the EU repo to check the DCC (https://github.pathcheck.org/debug.html), with the QR provided in this repo it validates, but it doesn't with any one I have tried.

The only visible difference in the provided QR and the one I am trying it's the "ver" property in the payload. The provided one has  '1.2.1', all the others have '1.0.0'.

The issue is on the IO side with a malformed or non standard QR generation? To note that all my QR are valid with the official italian app (VerificaC19).

Thanks in advance,
Matteo.

**Comment by astagi** [comment]
Hi @Epitaffio ,

that endpoint is the beginning of a list containing all the EU trusted certificates. You have to apply each certificate to your QR in order to verify the signature.. I rapidly wrote a script to do that (not so good, sorry), let me know if it works for you

```js
const fetch = require('node-fetch');
const rs = require('jsrsasign');
const rsu = require('jsrsasign-util');
const { DCC } = require('dcc-utils');

const main = async function () {
  const dcc = await DCC.fromImage('./data/your_certificate.png');
  let headers = {};
  let resp = null;
  do {
    resp = await fetch('https://get.dgc.gov.it/v1/dgc/signercertificate/update', {
      headers,
    })
    headers = {'X-RESUME-TOKEN' : resp.headers.get('x-resume-token')};
    const crt = `-----BEGIN CERTIFICATE-----\n${await resp.text()}\n-----END CERTIFICATE-----`;
    try {
      const verifier = rs.KEYUTIL.getKey(crt).getPublicKeyXYHex();
      const verified = await dcc.checkSignature(verifier);
      if (verified) {
        console.log(dcc.payload);
        break;
      }
    } catch {}
  } while (resp.status === 200);
};

main();
```

**Comment by nicetomytyuk** [comment]
Hi @astagi , actually by doing a `.GET` request to the `https://get.dgc.gov.it/v1/dgc/signercertificate/update` i get only one certificate returned so by trying to do any `checkSignature` i always get `Signature missmatch`.

Why the `do while` is needed?

**Comment by DevPGS** [comment]
> Hi @astagi , actually by doing a `.GET` request to the `https://get.dgc.gov.it/v1/dgc/signercertificate/update` i get only one certificate returned so by trying to do any `checkSignature` i always get `Signature missmatch`.
> 
> Why the `do while` is needed?

https://get.dgc.gov.it/v1/dgc/signercertificate/update returns the first valid certificate.
You must iterate over the X-RESUME-TOKEN header (sending the new X-RESUME-TOKEN to /update endpoint) until you get an invalid response from the server.
The complete list of valid KIDs of the day can be read at https://get.dgc.gov.it/v1/dgc/signercertificate/status

**Comment by nicetomytyuk** [comment]
@DevPGS thank you i was able to solve it, now the only issue is that by cycling for each certificates and trying to verify the dcc takes too long (2.28s) while the App seems to do it almost instantly..

**Comment by DevPGS** [comment]
yes, you need to cache the certificate list and update it every 24 hours.
see first task on `SDK` vertical line (translated as "Every 24 hours requires signing certificates and settings from backend") :
<img src="https://github.com/ministero-salute/it-dgc-verificac19-sdk-onboarding/raw/main/schema.png" alt="sdk-flow-schema">
(from https://github.com/ministero-salute/it-dgc-verificac19-sdk-onboarding )

**Comment by nicetomytyuk** [comment]
@DevPGS yeah actually i've set the API service i'm building to update all certificates and rules every 24h by caching them.
But still can't get how the app can be that faster in checking that the green pass signature is valid. 

Without the signature validation i get the data from the green pass in less than 300ms while with the validation it takes over 2 seconds for some of green passes.

The logic is the following:

reading the cached JSON of certirficates (all certificates are only the one which match x-kid in /status api)

then i cycle for each certificate in JSON file and do `checkSignature`

**Comment by DevPGS** [comment]
@nicetomytyuk, sorry I didn't use the dcc-utils, I developed my own library for php (https://github.com/herald-si/verificac19-sdk-php). 

As far as I know, dcc-util has been revised within the sdk for the node here: https://github.com/italia/verificac19-sdk.

if I remember correctly in the new library the logic has been changed and the correct KID of the list is targeted without iterating on each certificate

**Comment by nicetomytyuk** [comment]
@DevPGS oh didn't saw that node sdk, i'd give that immediatly a try, thank you
