### ISSUE TITLE
Angular bug

### ISSUE THREAD

**Issue by iCloudio** [ministero-salute/dcc-utils#14]
Angular CLI: 12.0.5
Node: 14.17.1
Package Manager: npm 6.14.13
OS: win32 x64

#### **Description**
Hi, i'm trying to use dcc-utils with new empty Angular app, but i get this error :
inherits_browser.js:5 --> Uncaught TypeError: Object prototype may only be an Object or null: undefined
![image](https://user-images.githubusercontent.com/92300194/136762425-c0d679d6-a66a-4458-8c4b-0a94c94ba476.png)
![image](https://user-images.githubusercontent.com/92300194/136762508-96792628-0b51-465b-84d7-166d3ece39e4.png)

#### **To Reproduce**

- ng new testangular
- cd testangular
- npm install dcc-utils
- in app.component.ts include library on top of file with
    const { DCC } = require('dcc-utils');
// and add
   constructor(){ console.log(DCC.fromRaw('dcc sample test string')); }

// ng serve now will produce first errors, that you can solve editing compiling options

- npm i -D @angular-builders/custom-webpack
- edit angular.json file in the root folder:

into architect.build --->
```
 "builder": "@angular-builders/custom-webpack:browser",
  "options": {
	  "customWebpackConfig": {
			  "path": "./custom-webpack.config.js"
	  },
  }
```
into  architect.serve --->
```
 "builder": "@angular-builders/custom-webpack:dev-server",
  "options": {
    "browserTarget": "app:build"
  },
```
- create a file in the root of angular folder, named custom-webpack.config.js containing this code
```
const webpack = require('webpack');
const path = require('path');

module.exports = {
    plugins: [
        new webpack.ProvidePlugin({
            process: 'process/browser',
        }),
    ],
    resolve: {
        alias: { util$: path.resolve(__dirname, 'node_modules/util') },
        //mainFields: ['browser', 'module', 'main'],
        fallback: {
            "fs": false,
            "stream": false,
            "path": false,
            "crypto": false,
            "assert": false,
            "http": false,
            "https": false,
            "zlib": false,
            "util": false,
            "node-inspect-extracted": false,
        }
    }
}
```

- run npm i --save-dev @types/node
- in tsconfig.app -> compiler options -> "types":["node"]
- run ng serve to reproduce my error

I need help to be able to use this library in an Angular project,
let me know if you need extra info, i will keep this issue update

Thank you for your precious help,
Ciao

**Comment by astagi** [comment]
@ClaudioB25 ok! let me know! (sorry for my late response)

**Comment by astagi** [comment]
@ClaudioB25 any update?

**Comment by ClaudioB25** [comment]
Ciao Andrea, non sono riuscito a risolvere, temo ci siano delle incompatibilità.
Ho ovviato creando un servizio apposito con node e Express e lo chiamo tramite http dalla mia app Angular.
Saluti

**Comment by mferraricloudsurfers** [comment]
Perchè avete chiuso la issue se il problema non è stato risolto? Ok il workaround, però un'integrazione corretta in Angular non sarebbe male, cosa ne dite?

**Comment by amammoli** [comment]
> Ciao Andrea, non sono riuscito a risolvere, temo ci siano delle incompatibilità. Ho ovviato creando un servizio apposito con node e Express e lo chiamo tramite http dalla mia app Angular. Saluti

ciao Claudio
ma con questo codice si riesce a capire anche se il greenpass è scaduto?

**Comment by astagi** [comment]
@amammoli si puoi controllare le date all'interno del certificato, poi ogni nazione può avere più o meno giorni di comporto a seconda delle regole nazionali. Per l'Italia sulla parte Node c'è questo https://github.com/italia/verificac19-sdk. Gli altri SDK ufficiali si trovano qua https://github.com/ministero-salute/it-dgc-verificac19-sdk-onboarding#lista-librerie

**Comment by amammoli** [comment]
ciao Andrea
grazie mille si ho verificato e funziona.
Ora credo ci saranno anche aggiornamenti relativi al super grenn pass....

Il giorno gio 9 dic 2021 alle ore 10:40 Andrea Stagi <
***@***.***> ha scritto:
