### ISSUE TITLE
Renderlo un SDK ufficiale?

### ISSUE THREAD

**Issue by dcannova** [ministero-salute/dcc-utils#16]
Stiamo testando da tempo in azienda un sistema di verifica green pass basato su dcc-utils.

Lo abbiamo integrato con la verifica della [signatures](https://get.dgc.gov.it/v1/dgc/signercertificate/update) e delle [rules](https://get.dgc.gov.it/v1/dgc/settings), il tutto incapsulato in un webservice che gira con express.

Node mi sembra la piattaforma più integrabile di tutte, è un bel problema cercare di integrare solo la versione Android.
Sarebbe bello rendere anche questo dcc-utils un SDK ufficiale da utilizzare in linea col DPCM del 12/10.

**Comment by lucadentella** [comment]
vedo che è stata aperta una issue simile anche nel repository dell'SDK, ne aggiungo qui il link per cross-reference:
https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/issues/24

**Comment by lucadentella** [comment]
Giuseppe

quella data di scadenza non è utilizzata in nessun processo di validazione: controlla il codice sorgente dell'app VerificaC19 per conferma. Il controllo sulla validità viene fatta scaricando le diverse durate (vaccinazione, tampone molecolare...) dal sito del Ministero.

**Comment by Giuseppe-1977** [comment]
Non è vero, testato su persona in quarantena. Controlli il codice.

Il sab 16 ott 2021, 09:34 lucadentella ***@***.***> ha
scritto:

**Comment by lucadentella** [comment]
Giuseppe

> E nella verifica da APP non ci sono regole differenziate se hai fatto vaccino o tampone molecolare

Qui trovi il codice dell'SDK.

**Comment by Giuseppe-1977** [comment]
Se guardi il boolean .isvalid trovi quello che dico. Dopo ti mando il codice su come viene valorizzato, sono fuori casa.  A stasera.

**Comment by Giuseppe-1977** [comment]
Sono riuscito a trovare un attimo di tempo.
Ho messo il break point navigando in debug.. da Android Studio...
E ti ho evidenziato la property del .ISVALID che ti dicevo.. e dentro oltre a tutto quello che hai detto c'è anche quella data di scadescanza recuperata dal CBOR. un JSON decriptato dalle chiavi pubblicate... via API JSON REST.
 
![Cattura](https://user-images.githubusercontent.com/13538548/137583636-9ffb075a-fda0-473c-b440-a0c9ee39f347.JPG)

Fammi sapere cosa ne pensi.

**Comment by lucadentella** [comment]
grazie, mi era sfuggito quel controllo preliminare.

> quindi non abbiamo un Green pass temporaneo e non scade dopo un anno dalla seconda dose. Come è possibile?

in realtà se guardi il codice che ti ho indicato sopra, il controllo sulla data viene fatto in base a **business rules** diverse per l'evento che ha generato il GP (vaccinazione...). L'SDK scarica periodicamente dal sito del Ministero un JSON con tutte le durate (in modo che sia possibile cambiarle, ad esempio quando hanno introdotto le 72 ore per i tamponi molecolari).

Nel caso che indichi (vaccinazione), ad esempio:

1) definisco le date di validità in base a quale dose è stata fatta, qui ad esempio se è la seconda:
```
                it.last().doseNumber >= it.last().totalSeriesOfDoses -> {
                    var startDate: LocalDate
                    var endDate: LocalDate
                    //j&j booster
                    if (it.last().medicinalProduct =="EU/1/20/1525" && it.last().doseNumber>it.last().totalSeriesOfDoses)
                    {
                         startDate = LocalDate.parse(clearExtraTime(it.last().dateOfVaccination))

                         endDate = LocalDate.parse(clearExtraTime(it.last().dateOfVaccination))
                             .plusDays(
                                 Integer.parseInt(getVaccineEndDayComplete(it.last().medicinalProduct))
                                     .toLong())
                    }
```
i metodi di lookup **(getVaccineEndDayComplete()**...) leggono i dati dal JSON:
```
    fun getVaccineEndDayComplete(vaccineType: String): String {
        return getValidationRules().find { it.name == ValidationRulesEnum.VACCINE_END_DAY_COMPLETE.value && it.type == vaccineType }?.value
            ?: run {
                ""
            }
    }
```
e quindi il GP è controllato in base a tali date (rispetto alla data odierna):
```
                    return when {
                        startDate.isAfter(LocalDate.now()) -> CertificateStatus.NOT_VALID_YET
                        LocalDate.now()
                            .isAfter(endDate) -> CertificateStatus.NOT_VALID
                        else -> CertificateStatus.VALID
                    }
                }
```
in definitiva quindi la logica è tutta implementata (_hardcoded_ nella implementazione italiana, usando un motore di business rules per altri stati), quel controllo preliminare sulla data di "scadenza" del GP attualmente fino al 2023 darà sempre esito positivo e non è realmente usato per consentire di variare le validità (un altro caso è quando hanno esteso a 365gg la validità del GP vaccinale) senza ri-emetterli.
bye

**Comment by Giuseppe-1977** [comment]
Ecco qui il JSON con i settings delle varie scadenze:

https://get.dgc.gov.it/v1/dgc/settings

Grazie per il prezioso confrontro.

**Comment by Giuseppe-1977** [comment]
Invece nella parte Node JS.. tutti questi controlli in che parte del codice li trovo? Perchè stavo guardando.. ma mi sfuggono.

**Comment by lucadentella** [comment]
se intendi la libreria in questione (dcc-utils), non ci sono: la libreria è già predisposta per valutare le regole in formato "europeo", vedi questo esempio:
https://github.com/ministero-salute/dcc-utils/blob/master/examples/check_rules_from_api.js

ma non essendo ancora caricate quelle italiane, è necessario implementare la logica nei propri client che utilizzano questa libreria (come ho fatto nel mio progetto https://github.com/lucadentella/raspberry-dgc )

**Comment by dcannova** [comment]
È interessante che una semplice richiesta abbia generato un thread così ricco.
Da qui si deduce un certo(direi ovvio) interesse per questa piattaforma, appunto più integrabile di tutte.
Quando ho scoperto che esisteva solo la versione Android, sono rimasto un po' scioccato.
Spero che si venga al punto del rendere le dcc-utils valide ai fini del DPCM del 12/10.

Perché?
1 - sono già solo ed unicamente una libreria, non un app con dentro una libreria.
2 - sono appunto integrabili in qualsiasi piattaforma/soluzione, mentre integrare una libreria di un app android dentro una soluzione al di fuori di android richiederebbe per forza di cose un minimo di rielaborazione del codice e quindi sostanzialmente un utilizzo non "puro" della libreria per com'è.
3 - in caso di controllo da parte delle autorità, è piuttosto facile dimostrare l'utilizzo delle librerie ufficiali anche aprendo semplicemente il package.json e al più controllando qualche chiamata alla libreria.

**Comment by lucadentella** [comment]
ciao

@FrancescoBonizzi l'allegato H del DPCM indica esplicitamente l'SDK Android (c'è addirittura il link al repo github) quindi per ora a norma di legge sei in regola solo se sviluppi la tua app usando tale SDK:

https://www.governo.it/sites/governo.it/files/Dpcm_12_ottobre_ALLEGATO_H.pdf

**Comment by Giuseppe-1977** [comment]
@dcannova 

Sicuramente, Il problema che se cambia il DPCM devi rimetterci le mani e sulle regole della validazione che qui in Italia è il CORE. Senza dubbio è un punto di partenza, ma siamo lontani da un servizio di integrazione snello che dovresti prendere cosi come è, senza entrare nelle logiche.  Quindi fin tanto che non rilasciano l'ufficilità dell'integrazione con NODE JS rimane un bel rischio interno soprattutto.

**Comment by FrancescoBonizzi** [comment]
Per me l'ideale sarebbe che validassero la libreria NodeJs, magari già con la definizione di una Web API autenticata, in modo che uno possa fare _clone_ e pubblicarla su qualunque host del mondo e se la interroghi.

**Comment by astagi** [comment]
Si, attualmente è possibile utilizzare solo l'SDK Android, ma ci stiamo muovendo per supportare anche Node e Python. A breve spero di darvi maggiori info.

**Comment by sirol81** [comment]
> Si, attualmente è possibile utilizzare solo l'SDK Android, ma ci stiamo muovendo per supportare anche Node e Python. A breve spero di darvi maggiori info.

sarebbe fantastico! ma visto che al momento come giustamente dici tu è ufficiale solo SDK android, si potrebbe avere qualche dritta anche nelle issues di là? siamo in molti a navigare in acque poco chiare (la documentazione su come referenziare gli oggetti è un po' carente) e bisogna scervellarsi sul progetto VerificaC19 per avere esempi concreti di come utilizzare il LoadKeysWorker e VerificationViewModel

**Comment by lcfr-dev** [comment]
Ciao ragazzi, io mi sono interfacciato con il sistema greenpass in luglio, quando ancora non si sapeva come sarebbe stato implementato in Italia. Non esistendo documentazione italiana, mi sono basato sul quella europea ([Link](https://ec.europa.eu/health/ehealth/covid-19_en)). Sono paratito dalla pagina indicata, per poi proseguire fino a studiare quasi tutto il sistema Greenpass. Per il caso dell'Italia, sono 3 le API da tenere in mente: [Status](https://get.dgc.gov.it/v1/dgc/signercertificate/status), [Update](https://get.dgc.gov.it/v1/dgc/signercertificate/update) e [Rules](https://get.dgc.gov.it/v1/dgc/settings). La status vi permette di ottenere gli identificatori dei certificati validi. La Update vi permette di ottenere la coppia KID-Certificate singolamente, e dovete farla finchè non ottenete l'errore 204. La rules/settings vi permette di ottenere le info per validare i greenpass (le rules italiane non seguono lo standard del green pass europeo, perciò dovrete sbatterci la testa). Per ottenere le coppie KID-Certificate usate un while, dovete passare solo un parametro ogni volta che è il `x-resume-token ` che trovate nella respose precedente.

**Comment by dcannova** [comment]
Nessuno mette in dubbio che grosso modo si deve procedere a questo maniera ed anche io ho fatto una cosa del genere, tuttavia la normativa vuole appunto che il codice sorgente che effettua tutto il processo di decodifica e validazione, sia al 100% una libreria ufficiale. Da qui tutto il senso di questo issue.

**Comment by lcfr-dev** [comment]
Sono d'accordo con te @dcannova, la mia risposta era per quelli che sono persi nei meandri del greenpass. Solo qui in italia si stanno ponendo così tanti limiti, altrove non si sono limitazioni del genere. Inoltre il greenpass è già lacunoso di suo, visto che può essere bypassato con facilità dai vaccinati positivi al covid (non scherzo) perchè non è MAI stato previsto un modo per revocare singoli certificati, ma solo dopo la scadenza. Un'esempio eclatante di questo BUG è l'app IO, che mantiene nelle comunicazioni tutti i green pass, permettendo a tutti i positivi/recovery che hanno ripreso (sfortunamente) il covid, di farla franca, visto che bastano delle foto, o soltanto usare un green pass valido.

**Comment by francescovgg** [comment]
> Si, attualmente è possibile utilizzare solo l'SDK Android, ma ci stiamo muovendo per supportare anche Node e Python. A breve spero di darvi maggiori info.

Buongiorno @astagi, c'è qualche novità su questo argomento? Grazie

**Comment by astagi** [comment]
Purtroppo ancora nessuna @francescovgg 😞

**Comment by astagi** [comment]
Temo che non sarà dcc-utils un sdk ufficiale... lavorando su questo progetto che lo utilizza https://github.com/astagi/verificac19-sdk poi lo passo per l'onboarding (qua i dettagli https://github.com/ministero-salute/it-dgc-verificac19-sdk-onboarding)
