### ISSUE TITLE
invalid CertLogic expression: undefined

### ISSUE THREAD

**Issue by belqit** [ministero-salute/dcc-utils#17]
```
    const dcc = await DCC.fromRaw(code.data);
    var myCert = require("./certificates.json")
    const verified = await dcc.checkSignatureWithKeysList(myCert);
    if (verified) {

        const VR_DE_0001_RULE_URL = "https://get.dgc.gov.it/v1/dgc/settings";
        const response = await fetch(VR_DE_0001_RULE_URL);
        const ruleJSON = await response.json();
        const rule = Rule.fromJSON(ruleJSON, {
            validationClock: new Date().toISOString(),
        });

        rule.evaluateDCC(dcc)
    }
```

la verifica del certificato funziona, ma restituisce questo errore nel momento in cui provo ad applicare le rules:

![image](https://user-images.githubusercontent.com/44238749/137593344-9b6243e7-7341-414d-bb89-01b6d8c7f582.png)

sto utilizzando node.js 14

**Comment by Lorenzo-Venturelli** [comment]
Questo errore è dato dal fatto che le business rules fornite dal gateway italiano NON sono in formato standard CertLogic, che è il formato definito dall'UE per la creazione di regole interoperabili.
Le utils presenti in questo repository implementano lo standard europeo, senza tenere conto del fatto che il gateway italiano fornisce un formato diverso di regole.

Da quanto ne so non c'è una API esposta dal gateway italiano per recuperare le regole in formato CertLogic al momento...

**Comment by lucadentella** [comment]
confermo, vedi #4 per una spiegazione approfondita.
In tale issue @astagi scriveva che le regole italiane sarebbero state rese disponibili, non so se si ha una previsione di data (vedo che anche l'SDK appena pubblicato le mantiene _hardcoded_)

**Comment by astagi** [comment]
Si esatto le regole italiane sono ancora hardcoded e l'unica variabile sono i settings presi da quella API. Purtroppo non ho aggiornamenti in merito all'upload delle rule in certlogic per l'Italia.
