### ISSUE TITLE
How to verify German covid certificate

### ISSUE THREAD

**Issue by aBuder** [ministero-salute/dcc-utils#22]
Hi,

I'm a bit lost here. I need to verify in our mobile app the covid certificate. Is there an step by step tutorial or an how to?

What I have to do, do verify German covid certificate?

**Comment by astagi** [comment]
Hi @aBuder , in order to verify your DCC you need to apply rules and signature verification to your DCC using this library. Have you tried to do that following the README? 

DCC Utils is just a set of utilities to work with DCC, any app can implement its solution using it.
