### ISSUE TITLE
Negative Test QR doesn't work

### ISSUE THREAD

**Issue by ClaudioB25** [ministero-salute/dcc-utils#23]
Hi, i have a green pass issued due to negative test that dcc-utils and covid-pass-verifier.com can't validate. It gives error on this two while VerificaC19 is working.

Please let me know, thanks

**Comment by astagi** [comment]
Hi @ClaudioB25 are you able to read its payload using dcc-utils? does it fail on signature verification?

**Comment by ClaudioB25** [comment]
Yes, it fails with error "Signature missmatch"

This is my code, it trigger the console.log in the catch

`
                    try {
			const verified = await dcc.checkSignature({
			  x: Buffer.from(signature.pub.x),
			  y: Buffer.from(signature.pub.y),
			  kid: Buffer.from(signature.kid),
			});
			console.log("verified", verified);
			if (verified) {
			  console.log(dcc.payload);
			  return(dcc.payload);
			  break;
			}
		  } catch (error){
			console.log("err" + error.message);
		  }`

**Comment by astagi** [comment]
@ClaudioB25 it looks like you are using wrong signatures.. try to get them from Italian backend

```js
const fetch = require('node-fetch');
const rs = require('jsrsasign');
const rsu = require('jsrsasign-util');
const { DCC } = require('dcc-utils');

const main = async function () {
  const dcc = await DCC.fromImage('./data/your_certificate.png');
  let headers = {};
  let resp = null;
  do {
    resp = await fetch('https://get.dgc.gov.it/v1/dgc/signercertificate/update', {
      headers,
    })
    headers = {'X-RESUME-TOKEN' : resp.headers.get('x-resume-token')};
    const crt = `-----BEGIN CERTIFICATE-----\n${await resp.text()}\n-----END CERTIFICATE-----`;
    try {
      const verifier = rs.KEYUTIL.getKey(crt).getPublicKeyXYHex();
      const verified = await dcc.checkSignature(verifier);
      if (verified) {
        console.log(dcc.payload);
        break;
      }
    } catch {}
  } while (resp.status === 200);
};

main();
```

**Comment by astagi** [comment]
@ClaudioB25 alternatively you can use [verificac19-sdk](https://github.com/italia/verificac19-sdk).

**Comment by qippur** [comment]
Looks like the code snippet keeps downloading certificates until the key of one of them 
- verifies the signature or 
- there are no more certificates to download

Am I right?

Is there a chance to get the correct certificate in "one shot" (either from a pre-downloaded list of certificates or by setting the correct x-resume-token and fetching the right certificate from the update URL) once the KID is retrieved from the DCC (a.k.a. Green Pass)?
(sorry for any lack of etiquette - I am very new to this all)

**Comment by astagi** [comment]
@qippur yes, it's possible but is out of DCCUtils scope, if you want to provide one shot verification using our backend please switch to [verificac19-sdk](https://github.com/italia/verificac19-sdk).

**Comment by ClaudioB25** [comment]
I tested 

> 

Same error, Signature mismatch

**Comment by astagi** [comment]
sorry @ClaudioB25 the function is `checkSignatureWithCertificate`, I've just updated the code! The code I provided before was too old!

```js
const fetch = require('node-fetch');
const rs = require('jsrsasign');
const rsu = require('jsrsasign-util');
const { DCC } = require('dcc-utils');

const main = async function () {
  const dcc = await DCC.fromImage('./data/your_certificate.png');
  let headers = {};
  let resp = null;
  do {
    resp = await fetch('https://get.dgc.gov.it/v1/dgc/signercertificate/update', {
      headers,
    })
    headers = {'X-RESUME-TOKEN' : resp.headers.get('x-resume-token')};
    const crt = `-----BEGIN CERTIFICATE-----\n${await resp.text()}\n-----END CERTIFICATE-----`;
    try {
      const verifier = rs.KEYUTIL.getKey(crt).getPublicKeyXYHex();
      const verified = await dcc.checkSignatureWithCertificate(verifier);
      if (verified) {
        console.log(dcc.payload);
        break;
      }
    } catch {}
  } while (resp.status === 200);
};

main();
```

**Comment by astagi** [comment]
Sorry @ClaudioB25 the code I provided is a bit old. Try using `checkSignatureWithCertificate`

```js
const main = async function () {
  const dcc = await DCC.fromImage('./test/your_dcc.png');
  let headers = {};
  let resp = null;
  do {
    resp = await fetch('https://get.dgc.gov.it/v1/dgc/signercertificate/update', {
      headers,
    })
    headers = {'X-RESUME-TOKEN' : resp.headers.get('x-resume-token')};
    const crt = `-----BEGIN CERTIFICATE-----\n${await resp.text()}\n-----END CERTIFICATE-----`;
    try {
      const verified = await dcc.checkSignatureWithCertificate(crt);
      if (verified) {
        console.log(dcc.payload);
        break;
      }
    } catch {}
  } while (resp.status === 200);
};

main();

```

**Comment by ClaudioB25** [comment]
Tested, same error with vaccined green pass and covid test green pass

Error: Signature missmatch
    at doVerify (C:\Kairos\greenpass\node_modules\dcc-utils\node_modules\cose-js\lib\sign.js:173:13)
    at verifyInternal (C:\Kairos\greenpass\node_modules\dcc-utils\node_modules\cose-js\lib\sign.js:291:5)
    at C:\Kairos\greenpass\node_modules\dcc-utils\node_modules\cose-js\lib\sign.js:220:14
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async verifyGreenPass (C:\Kairos\greenpass\green_pass_tester.js:44:24)
    at async C:\Kairos\greenpass\green_pass_tester.js:19:13

**Comment by astagi** [comment]
That's really strange @ClaudioB25 ... I can't ask you to pass me your certificate, it contains sensible data, however we can schedule a call and see what's happening. Please DM me on Twitter (https://twitter.com/4stagi).

**Comment by AndreaElia1** [comment]
Hi,
i have the same error "Signature missmatch" for the code:

const verified = await dcc.checkSignature({
      x: Buffer.from(signature.pub.x),
      y: Buffer.from(signature.pub.y),
      kid: Buffer.from(signature.kid),
  });


I would like to know how you solved it, thanks.

**Comment by ClaudioB25** [comment]
Hi AndreaElia, 
on the code above you have to replace this line: 
const crt = `-----BEGIN CERTIFICATE-----\n${await resp.text()}\n-----END CERTIFICATE-----`;
with 
const crt = `-----BEGIN CERTIFICATE-----${await resp.text()}-----END CERTIFICATE-----`;

The script is slow because it need to download a cert every do while cycle, i make a function that download all certificates in memory when i start the service(yesterday i counted 350 http call to verify one qr code)

**Comment by ClaudioB25** [comment]
I posted a sample, if you want you can check at 
https://github.com/ClaudioB25/Node-Green-Pass-Validator

**Comment by AndreaElia1** [comment]
@ClaudioB25 Thank you very much
