### ISSUE TITLE
green pass in black list

### ISSUE THREAD

**Issue by AndreaElia1** [ministero-salute/dcc-utils#25]
# Issue content
I wanted to know how to check if the green pass is valid by checking with the black list.

Can anyone tell me how and where to get the updated black list?

**Comment by DevPGS** [comment]
the blacklist is there: https://get.dgc.gov.it/v1/dgc/settings (black_list_uvci)
the revoked list is more complex to obtain, you must follow this documentation https://github.com/ministero-salute/it-dgc-documentation/blob/master/DRL.md

[here ](https://github.com/italia/verificac19-sdk) an official node-js sdk that checks those blacklist/revoked lists.

**Comment by astagi** [comment]
Grazie @DevPGS
