### ISSUE TITLE
Get the specific country rules

### ISSUE THREAD

**Issue by C1AFFA** [ministero-salute/dcc-utils#4]
Hi :)
First of all, great work with this utils!
Is there a way to fetch a valid set of rules for a specific country? 
It could be useful to implement this feature. 
The rules system is not very intuitive and the possibility to have access to official rule sets . 
Am I missing something and there is a way? Or, for some reason, is not possible?

Thanks :)

**Comment by lcfr-dev** [comment]
Hi, there aren specific EU API, but it is impossible find an alone api where u can find the needed data because every country follow a different way. [this is EU](https://dgca-businessrule-service.cfapps.eu10.hana.ondemand.com/rules), [This is IT](https://get.dgc.gov.it/v1/dgc/settings).

**Comment by Epitaffio** [comment]
> 
> 
> Hi, there aren specific EU API, but it is impossible find an alone api where u can find the needed data because every country follow a different way. [this](https://dgca-businessrule-service.cfapps.eu10.hana.ondemand.com/rules) is EU rules list (all start there), [This is IT](https://get.dgc.gov.it/v1/dgc/settings).
> To get the list of a specific country https://dgca-businessrule-service.cfapps.eu10.hana.ondemand.com/rules/CoutryCode
> To get a specific rule https://dgca-businessrule-service.cfapps.eu10.hana.ondemand.com/rules/_CountryCode_/Hash
> **Example**
> _https://dgca-businessrule-service.cfapps.eu10.hana.ondemand.com/rules/at/e11627ad34f364c5f637a4bca37e2aa2661e369dce7012f76fba62e48f8e91ad_
> 
> [This ](https://www.getpostman.com/collections/fba85cb4db1dd7b802ac) is my personal collection of DGC API on postman

I have just come across the same results, so right now we can't leverage on this library to check the italian rules because they aren't in that list, that's right?

Analyzing the VerificaC19 android app it's seem the rules and their validation are hardcoded in the code like here:
https://github.com/ministero-salute/it-dgc-verificaC19-android/blob/develop/app/src/main/java/it/ministerodellasalute/verificaC19/ui/main/verification/VerificationViewModel.kt#L207


So we can't use this library at it's full and we need to just hardcode the checks, I am right?

**Comment by lcfr-dev** [comment]
you are right, it's unknown why Italy followed a different way, but they only complicated rule handling and made it less flexible to future changes. I wrote a different library because this one at the moment was not avaliable

**Comment by C1AFFA** [comment]
> Hi, there aren specific EU API, but it is impossible find an alone api where u can find the needed data because every country follow a different way. [this](https://dgca-businessrule-service.cfapps.eu10.hana.ondemand.com/rules) is EU rules list (all start there), [This is IT](https://get.dgc.gov.it/v1/dgc/settings).
> To get the list of a specific country https://dgca-businessrule-service.cfapps.eu10.hana.ondemand.com/rules/CoutryCode
> To get a specific rule https://dgca-businessrule-service.cfapps.eu10.hana.ondemand.com/rules/_CountryCode_/Hash
> **Example**
> _https://dgca-businessrule-service.cfapps.eu10.hana.ondemand.com/rules/at/e11627ad34f364c5f637a4bca37e2aa2661e369dce7012f76fba62e48f8e91ad_
> 
> [This ](https://www.getpostman.com/collections/fba85cb4db1dd7b802ac) is my personal collection of DGC API on postman

Oh, this is nice, thank you! I guess that Italy will update the Verification app every time a rule change occours..


> > Hi, there aren specific EU API, but it is impossible find an alone api where u can find the needed data because every country follow a different way. [this](https://dgca-businessrule-service.cfapps.eu10.hana.ondemand.com/rules) is EU rules list (all start there), [This is IT](https://get.dgc.gov.it/v1/dgc/settings).
> > To get the list of a specific country https://dgca-businessrule-service.cfapps.eu10.hana.ondemand.com/rules/CoutryCode
> > To get a specific rule https://dgca-businessrule-service.cfapps.eu10.hana.ondemand.com/rules/_CountryCode_/Hash
> > **Example**
> > _https://dgca-businessrule-service.cfapps.eu10.hana.ondemand.com/rules/at/e11627ad34f364c5f637a4bca37e2aa2661e369dce7012f76fba62e48f8e91ad_
> > [This ](https://www.getpostman.com/collections/fba85cb4db1dd7b802ac) is my personal collection of DGC API on postman
> 
> I have just come across the same results, so right now we can't leverage on this library to check the italian rules because they aren't in that list, that's right?
> 
> Analyzing the VerificaC19 android app it's seem the rules and their validation are hardcoded in the code like here:
> https://github.com/ministero-salute/it-dgc-verificaC19-android/blob/develop/app/src/main/java/it/ministerodellasalute/verificaC19/ui/main/verification/VerificationViewModel.kt#L207
> 
> So we can't use this library at it's full and we need to just hardcode the checks, I am right?

I guess not. Just for decode qr and signature validation. Anyway, the law says that you must use the Verifica19 app. If you want to handle other logics, like registration people's name registration (required by law for events), I guess that you need to perform a double check (first with VerificaC19 then with your implementation) . But this is just a guess... it's not very clear, for me, right now.

**Comment by astagi** [comment]
Hi @C1AFFA @lcfr-dev @Epitaffio yes Italy hasn't onboarded certlogic rules to EU, they'll be available soon.

Anyway I added a new feature to build rules from raw JSON so you can create new Rules from the EU API  https://github.com/ministero-salute/dcc-utils/pull/6 (we don't provide specific methods to fetch EU endpoints in this library atm) . Let me know what you think.
