### ISSUE TITLE
Question about the content  of CI on Green Pass

### ISSUE THREAD

**Issue by loreberti89** [ministero-salute/dcc-utils#9]
# Issue content
Hello I've a question on content of GreenPass.
In my Green Pass, i can see an Unique Certificate Identifier, that I can see also after decoding with key "CI".
But what does it contain?

I have read this [https://ec.europa.eu/health/sites/default/files/ehealth/docs/vaccination-proof_interoperability-guidelines_en.pdf](https://ec.europa.eu/health/sites/default/files/ehealth/docs/vaccination-proof_interoperability-guidelines_en.pdf) and I can see that there are 3 versions.

But did all countries choose one of these or each country choose their own?
In this case, Which one did Italy choose?

**Comment by loreberti89** [comment]
I have found this link, that answer to my question:
https://www.governo.it/sites/governo.it/files/Green_Pass_all_D.pdf

**Comment by astagi** [comment]
@loreberti89 sorry! I missed notifications on this issue, my bad! Yes, that's the right document. For further questions about DCC that are not related to technical issue of this library please use our forum or open an issue/PR [here](https://github.com/ministero-salute/it-dgc-documentation) if something's missing! Thank you!
